### PR TITLE
Removed uninitialized and global variables in code

### PR DESCRIPTION
**Pull request by RussDragon**
I am sorry for so many PRs but my strict-checking found more global/unused variables. I've commented some uninitialized variables in table constructor and moved tag to local scope of XmlParser.

### CODE REVIEW

**Comment by manoelcampos** [comment]
Don't be sorry and thanks for the contribution.

**Comment by RussDragon** [comment]
I've closed this PR because I am not sure about my fixes, please check this issue
https://github.com/manoelcampos/xml2lua/issues/16

**Comment by manoelcampos** [comment]
Ok. I'll need some time to take a look at it because I'm in a run. I return to you ASAP.

**Comment by RussDragon** [comment]
Alright, I will be waiting for you!

**Pull request closed without merging**
