### PR TITLE
Update xml2lua-v1.5-0.rockspec

### PR DESCRIPTION
**Pull request by ur4ltz**
Incorrect version number v1.5-0.. #58

### CODE REVIEW

**Comment by manoelcampos** [comment]
Hello @ur4ltz. Thanks for the contribution.
In this case, I think it's better to update the version for 1.5-1, since there are devs using the v1.5-0.
Furthermore, it would be better to remove the "v" from the roskcspec filename too.

**Comment by manoelcampos** [comment]
By the way, is it just a matter of standard for luarocks or is it causing some issue?

**Comment by ur4ltz** [comment]
Hi!
I think it will be right.

**Comment by ur4ltz** [comment]
> By the way, is it just a matter of standard for luarocks or is it causing some issue?

https://github.com/manoelcampos/xml2lua/issues/58

**Comment by manoelcampos** [comment]
I couldn't get what the actual issue is, but I'm ok with the change in version number format.

**Comment by ur4ltz** [comment]
> I couldn't get what the actual issue is, but I'm ok with the change in version number format.

https://github.com/luarocks/luarocks/wiki/Rockspec-format

**Comment by manoelcampos** [comment]
Now I see the standard doesn't expect a "v" in version number.
However, I suppose the actual issue is that when you try to download the rock sources, they are not being found due to this "v". Please clarify.

**Comment by ur4ltz** [comment]
> Now I see the standard doesn't expect a "v" in version number.
> However, I suppose the actual issue is that when you try to download the rock sources, they are not being found due to this "v". Please clarify.

Yes!
And rename file from "xml2lua-v1.x-x.rockspec"  to "xml2lua-1.x-x.rockspec"!.

**Review by manoelcampos — APPROVED** [review]

**Comment by manoelcampos** [comment]
I've just finished the changes and merged.
Thanks for contributing.
The new 1.5-1 version will be available in luarocks automatically.

**Pull request merged**
