### PR TITLE
Close #46: Add minimal acceptance tests and fix lint warning

### LINKED ISSUE #46: General lint suggestions
Hi there,

I'm planning to use this library to parse MPEG-Dash manifests, and I ran a lint tool over the source files looking for potential memory leak and others, I couldn't find any but there are some issues I think that we can solve.

I'm gonna list them here and if you're okay, I can make a `PR` fixing those issues.

# XmlParser.lua

## Shadowing upvalue
```lua
--  XmlParser.lua:131:26: shadowing upvalue err on line 131
local function err(self, err, pos)
    if self.options.errorHandler then
        self.options.errorHandler(err,pos)
    end
end
```
**Suggestion**: rename either the function or parameter.

## Variable previously defined
```lua
--     XmlParser.lua:252:27: variable i was previously defined as a loop variable on line 251
local function _parseDtd(self, xml, pos)
    -- match,endMatch,root,type,name,uri,internal
    local dtdPatterns = {self._DTD1, self._DTD2, self._DTD3, self._DTD4, self._DTD5}

    for i, dtd in pairs(dtdPatterns) do
        local m,e,r,t,n,u,i = string.find(xml, dtd, pos)
        if m then
            return m, e, {_root=r, _type=t, _name=n, _uri=u, _internal=i} 
        end
    end

    return nil
end
```
**Suggestion**: rename either the the first `i` or the second.

## Setting non-standard global variable

```lua
--     XmlParser.lua:262:26: setting non-standard global variable attrs
local function parseDtd(self, xml, f)
    f.match, f.endMatch, attrs = _parseDtd(self, xml, f.pos)
    if not f.match then 
        err(self, self._errstr.dtdErr, f.pos)
    end 

    if fexists(self.handler, 'dtd') then
        local tag = {name="DOCTYPE", value=string.sub(xml, f.match+10, f.endMatch-1)}
        self.handler:dtd(tag, f.match, f.endMatch)
    end
end
```
**Suggestion**: since the `attrs` is not used we could replace it with `_`.

# xml2lua.lua

## Variable was previously defined

```lua
--     xml2lua.lua:151:9: variable attrTable was previously defined as an argument on line 149
local function attrToXml(attrTable)
  local s = ""
  local attrTable = attrTable or {}
  
  for k, v in pairs(attrTable) do
      s = s .. " " .. k .. "=" .. '"' .. v .. '"'
  end
  return s
end
```
**Suggestion**: just remove the `local` keyword.

```lua
--    xml2lua.lua:179:9: variable level was previously defined as an argument on line 178
function xml2lua.toXml(tb, tableName, level)
  local level = level or 1
  local firstLevel = level
  local spaces = string.rep(' ', level*2)
  local xmltb = level == 1 and {'<'..tableName..'>'} or {}
```
**Suggestion**: just remove the `local` keyword.

### PR DESCRIPTION
**Pull request by leandromoreira**
# Close #46

In order to proceed with the lint fix, I introduced just two general acceptance tests using busted and running them in docker. I was afraid to break anything and these tests can help mitigate a little bit this fear, the idea is to adding up more use cases so when we do a change to the library we can test against it.

### CODE REVIEW

**Comment by leandromoreira** [comment]
https://github.com/manoelcampos/xml2lua/issues/46

**Comment by leandromoreira** [comment]
Now one can also run:

```bash
make lint # to check lint mistakes
make test # to run the tests
```

**Comment by manoelcampos** [comment]
Hello @leandromoreira, 
I've just merged the PR.
Everything worked great here. Thanks for that.

It would be nice to run the test on the CI using a GitHub Action.
I'll do that if I make some time.

**Comment by manoelcampos** [comment]
Only after merging I realized some details and we could clean up a bit.

## Makefile

I don't think this is required.

```
- run:
	docker-compose down && docker-compose build nginx && docker-compose run --rm --service-ports nginx
```

## Dockerfile.test

I didn't see the container using git, so, this command doesn't seem to be required.
`git config --global url."https://".insteadOf git:// \`

**Comment by leandromoreira** [comment]
@manoelcampos thanks you're right I carried that over from my last lua project, about the build system we can use travis https://github.com/leandromoreira/resty-bakery but you must connect to travis and hook the project there and then it's simple as to add the https://github.com/leandromoreira/resty-bakery/blob/master/.travis.yml file

Maybe we need to remove the lint step since it might break the build =/ .

**Comment by manoelcampos** [comment]
Ok. I remove those lines.
About the CI, I prefer GitHub Actions because they are easier to setup.
I'll do that. Thanks.

**Comment by leandromoreira** [comment]
I think the tests can help us, I was wondering to discuss with you if we can change the table to string xml parser behavior. Today it expands a single node from [`<node attr="a" />` to `<node attr="a">\n</node>`](https://github.com/manoelcampos/xml2lua/blob/master/spec/acceptance_test_spec.lua#L29) is there any reason for that?

**Comment by manoelcampos** [comment]
No, there isn't. Probably it was the easiest way to implement that.

**Comment by manoelcampos** [comment]
By the way, it's tricky to check if after converting XML -> Lua -> XML, the result will be the same as the original XML. Check commit d536894 for details.

**Comment by manoelcampos** [comment]
In fact, I already had travis enabled. I just changed as you showed.

**Comment by manoelcampos** [comment]
> I think the tests can help us, I was wondering to discuss with you if we can change the table to string xml parser behavior. Today it expands a single node from [`<node attr="a" />` to `<node attr="a">\n</node>`](https://github.com/manoelcampos/xml2lua/blob/master/spec/acceptance_test_spec.lua#L29) is there any reason for that?
> 
> 

About that, after parsing an XML to lua, we lose information if the tag is a regular or auto-closing one. This way, after converting back to XML, the only option is to generate them as regular tags.

**Comment by leandromoreira** [comment]
> About that, after parsing an XML to lua, we lose information if the tag is a regular or auto-closing one. This way, after converting back to XML, the only option is to generate them as regular tags.

Are we able to check if the node/table member has value/children? if we are we can auto close any node without value/children

**Comment by leandromoreira** [comment]
```lua
local simple_lua_with_attributes = {
  {age=42, name="Manoela", salary=42.1, city="Brasília-DF", _attr={ type="legal" }, music={_attr={like="true"}} },
  {age=42, name="Manoel", salary=42.1, city="Palmas-TO", _attr={ type="natural" }, music={_attr={like="true"}} },
}
```

we can assume that given a member where its value is a table holding only `_attr` member can be declared auto closable, what do you think?

**Comment by leandromoreira** [comment]
I need to give you a heads up that I'm advocating for that because my use case ([mpeg-dash manifests](https://github.com/leandromoreira/resty-bakery/blob/master/spec/manifests/generic_dash.mpd#L42)) has single node to represent segments.

Also I noticed what seems like a bug, I guess, because the deeper it gets the more spaces it'll add, you can [try to parse this](https://raw.githubusercontent.com/leandromoreira/resty-bakery/master/spec/manifests/generic_dash.mpd) into table and then back to xml to see what I'm tallking about.

To overcome some of these ^ I did some [minimal transformations](https://github.com/leandromoreira/resty-bakery/blob/master/src/resty-bakery-dash.lua#L55-L63) over the xml.

**Comment by manoelcampos** [comment]
> Are we able to check if the node/table member has value/children? if we can, we coud auto close any node without value/children

Yes, we are, by just using #node the get the number of children.

> ```lua
> local simple_lua_with_attributes = {
>   {name="Manoela", city="Brasília-DF", _attr={ type="legal" }, music={_attr={like="true"}} },
>   {name="Manoel", city="Palmas-TO", _attr={ type="natural" }, music={_attr={like="true"}} },
> }
> ```
> 
> 
> we can assume that given a member where its value is a table holding only _attr member can be declared auto closable, what do you think?

Makes sense, simplifying the generated XML. But if you want to ensure that when converting XML -> Lua -> XML, the resulting XML is equal to the original, it won't because some details are lost during conversion.

A node in the source XML may have only attributes and be declared as a regular tag anyway. After the round-trip conversion, it will be converted to auto-closing tag.

> I need to give you a heads up though, I'm advocating for that because my use case ([mpeg-dash manifests](https://github.com/leandromoreira/resty-bakery/blob/master/spec/manifests/generic_dash.mpd#L42)) has single node to represent segments.

Well, auto-closing tags are simpler and I don't see any issue assuming that.

> Also I noticed what seems like a bug, I guess, because the deeper it gets the more spaces it'll add, you can [try to parse this](https://raw.githubusercontent.com/leandromoreira/resty-bakery/master/spec/manifests/generic_dash.mpd) into table and then back to xml to see what I'm tallking about.
> 
> To overcome some of these ^ I did some [minimal transformations](https://github.com/leandromoreira/resty-bakery/blob/master/src/resty-bakery-dash.lua#L55-L63) over the xml.

This case I think is just about getting an organized XML, but we can improve the identation. I take a look at it.

**Comment by manoelcampos** [comment]
I couldn't see these double new lines you are talking about.
Despite the missing `<?xml>`, result is almost the same as the original XML.

**Pull request closed without merging**
